version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: ruby
    versions:
    - ">= 2.8"
- package-ecosystem: docker
  directory: "/ci/ruby2.7"
  schedule:
    interval: daily
  ignore:
  - dependency-name: ruby
    versions:
    - ">= 2.8"
