version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: ruby
    versions:
    - ">= 3.1"
- package-ecosystem: docker
  directory: "/ci/ruby3.0"
  schedule:
    interval: daily
  ignore:
  - dependency-name: ruby
    versions:
    - ">= 3.1"
