rspec_task:
  container:
    matrix:
      dockerfile: ci/ruby2.6/Dockerfile
      dockerfile: ci/ruby2.7/Dockerfile
      dockerfile: ci/ruby3.0/Dockerfile
      dockerfile: ci/ruby3.1/Dockerfile
      dockerfile: ci/ruby3.2/Dockerfile
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script: echo $RUBY_VERSION && cat Gemfile.lock
    populate_script: bundle config force_ruby_platform true && bundle install
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  precompile_script: bin/rails assets:precompile
  rspec_script: bundle exec rspec
