rspec_task:
  container:
    matrix:
      dockerfile: ci/ruby3.1/Dockerfile
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script: echo $RUBY_VERSION && cat Gemfile.lock
    populate_script: bundle config force_ruby_platform true && bundle config build.nokogiri --use-system-libraries && bundle install
  rspec_script: bundle exec rspec
